---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: auraperfume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: mohammedmusa1/perfume-notification-service:latest
          ports:
            - containerPort: 3007
          envFrom:
            - configMapRef:
                name: auraperfume-config
            - secretRef:
                name: auraperfume-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 3007
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: auraperfume
spec:
  selector:
    app: notification-service
  ports:
    - port: 3007
      targetPort: 3007
  type: ClusterIP
