---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: auraperfume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: mohammedmusa1/perfume-order-service:latest
          ports:
            - containerPort: 3004
          envFrom:
            - configMapRef:
                name: auraperfume-config
            - secretRef:
                name: auraperfume-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: auraperfume
spec:
  selector:
    app: order-service
  ports:
    - port: 3004
      targetPort: 3004
  type: ClusterIP
