---
# All auraperfume namespace secrets
apiVersion: v1
kind: Secret
metadata:
  name: auraperfume-secrets
  namespace: auraperfume
type: Opaque
stringData:
  POSTGRES_USER: "auraperfume_user"
  POSTGRES_PASSWORD: "auraperfume_secret_2024"
  POSTGRES_DB: "auraperfume"
  DATABASE_URL: "postgresql://auraperfume_user:auraperfume_secret_2024@postgres:5432/auraperfume"
  JWT_SECRET: "aura-perfume-jwt-secret-change-in-production-2024"
  JWT_REFRESH_SECRET: "aura-perfume-refresh-secret-change-in-production-2024"
  RAZORPAY_KEY_ID: "rzp_test_SvDHRw08qyVnPl"
  RAZORPAY_KEY_SECRET: "B3Im5UWbcjYAeGDq58nfKXhi"
  SMTP_USER: "shaikhmusa991@gmail.com"
  SMTP_PASS: "ztmn tjml eako bwva"
  GMAIL_USER: "shaikhmusa991@gmail.com"
  GMAIL_APP_PASSWORD: "ztmn tjml eako bwva"
